FROM node:14 as node

ENV NODE_ENV development

WORKDIR /app

COPY ./package.json /app
COPY ./package-lock.json /app/package-lock.json
RUN npm install

COPY . .

EXPOSE 3000
CMD ["npm", "run", "start:dev"]